// project/src/screens/LandingPage/sections/AppOverviewSection/AppOverviewSection.tsx
import { Building2Icon, LockIcon, MailIcon, UserIcon } from "lucide-react";
import React from "react";
import { Button } from "../../../../components/ui/button";
import { Card, CardContent } from "../../../../components/ui/card";
import { Input } from "../../../../components/ui/input";
import { Label } from "../../../../components/ui/label";
import { Textarea } from "../../../../components/ui/textarea";
import { useScrollAnimation } from "../../../../hooks/useScrollAnimation";

const formFields = [
  {
    id: "fullName",
    label: "Nombre completo",
    placeholder: "Ingresa tu nombre completo",
    icon: UserIcon,
    type: "input",
  },
  {
    id: "companyName",
    label: "Nombre de la empresa",
    placeholder: "Ingresa el nombre de tu empresa",
    icon: Building2Icon,
    type: "input",
  },
  {
    id: "phone",
    label: "Teléfono de contacto",
    placeholder: "Ingresa tu número de teléfono",
    icon: LockIcon,
    type: "input",
  },
  {
    id: "email",
    label: "Correo electrónico",
    placeholder: "Ingresa tu correo electrónico",
    icon: MailIcon,
    type: "input",
  },
  {
    id: "businessDescription",
    label: "Cuéntanos un poco sobre tu negocio",
    placeholder: "Describe lo que hace tu negocio",
    icon: null,
    type: "textarea",
  },
];

export const AppOverviewSection = (): JSX.Element => {
  const { elementRef, isVisible } = useScrollAnimation();

  return (
    <section
      id="contacto"
      ref={elementRef}
      className={`w-full flex flex-col lg:flex-row items-center gap-8 md:gap-12 lg:gap-[122px] px-4 md:px-12 lg:px-[130px] py-8 md:py-16 lg:py-[93px] mb-8 md:mb-16 lg:mb-24 bg-[#ffffff17] rounded-[30px] md:rounded-[60px] transition-all duration-1000 ${
        isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'
      }`}>
      <div className="flex flex-col w-full lg:w-[724px] items-start gap-6 md:gap-11">
        <h2 className="self-stretch font-medium text-white text-2xl md:text-3xl lg:text-5xl tracking-[0] leading-tight md:leading-[57px] flex items-center justify-center [font-family:'Funnel_Display',Helvetica]">
          ¿Listo para llevar tu negocio al siguiente nivel?
        </h2>

        <p className="w-full lg:w-[538px] [font-family:'Degular-Regular',Helvetica] font-normal text-white text-base md:text-xl lg:text-2xl tracking-[0] leading-relaxed md:leading-[37px]">
          Déjanos tus datos y te ayudaremos a resolver tus dudas o iniciar el
          proceso de contratación.
          <br />
          <br />
          Te contactaremos lo más pronto posible para apoyarte en todo lo que
          necesites.
        </p>
      </div>

      <Card className="w-full lg:w-[520px] bg-[#fefefe] rounded-[20px] md:rounded-[40px] border-0">
        <CardContent className="pt-8 md:pt-10 lg:pt-12 px-4 md:px-6 lg:px-[50px] pb-8 md:pb-10 lg:pb-[50px]">
          <form className="flex flex-col gap-4 md:gap-5 lg:gap-5">
            {formFields.map((field) => (
              <div key={field.id} className="flex flex-col gap-3 md:gap-4 lg:gap-4">
                <Label
                  htmlFor={field.id}
                  className="[font-family:'Degular-Semibold',Helvetica] text-base md:text-lg lg:text-xl tracking-[0.49px] leading-[17.1px] font-normal text-[#1a1a1a]"
                >
                  {field.label}
                </Label>
                <div className="relative">
                  {field.type === "input" ? (
                    <Input
                      id={field.id}
                      placeholder={field.placeholder}
                      className="h-12 md:h-12 lg:h-[50px] rounded-[7.31px] border-[1.22px] border-[#d2d2d2] [font-family:'Inter',Helvetica] font-normal text-[#767676] text-sm md:text-sm lg:text-base tracking-[-0.35px] leading-[31.7px] pr-12 md:pr-[55px]"
                    />
                  ) : (
                    <Textarea
                      id={field.id}
                      placeholder={field.placeholder}
                      className="h-24 md:h-24 lg:h-[90px] rounded-[7.31px] border-[1.22px] border-[#d2d2d2] [font-family:'Inter',Helvetica] font-normal text-[#767676] text-sm md:text-sm lg:text-base tracking-[-0.35px] leading-[31.7px] resize-none"
                    />
                  )}
                  {field.icon && (
                    <field.icon className="absolute right-[19px] top-1/2 -translate-y-1/2 w-6 h-6 text-[#767676]" />
                  )}
                </div>
              </div>
            ))}

            <Button
              type="submit"
              className="h-12 md:h-12 lg:h-[50px] mt-2 md:mt-3 rounded-[70px] bg-[linear-gradient(343deg,rgba(255,136,170,1)_0%,rgba(107,78,230,1)_73%)] [font-family:'Urbanist',Helvetica] font-semibold text-colorwhite-100 text-base md:text-lg lg:text-xl tracking-[0] leading-[31.7px] hover:opacity-90"
            >
              Enviar
            </Button>
          </form>
        </CardContent>
      </Card>
    </section>
  );
};

// src/app/web/app-overview-section/app-overview-section.component.ts
import { Component, AfterViewInit, ElementRef, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

interface FormData {
  fullName: string;
  companyName: string;
  phone: string;
  email: string;
  businessDescription: string;
}

@Component({
  selector: 'app-app-overview-section',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './app-overview-section.component.html',
  styleUrls: ['./app-overview-section.component.css']
})
export class AppOverviewSectionComponent implements AfterViewInit {
  @ViewChild('section') section!: ElementRef;
  isVisible = false;

  formData: FormData = {
    fullName: '',
    companyName: '',
    phone: '',
    email: '',
    businessDescription: ''
  };

  ngAfterViewInit() {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          this.isVisible = true;
        }
      },
      { threshold: 0.1 }
    );

    if (this.section) {
      observer.observe(this.section.nativeElement);
    }
  }

  onSubmit() {
    console.log('Form submitted:', this.formData);
    
    alert('¡Gracias por tu interés! Nos pondremos en contacto contigo pronto.');
    this.formData = {
      fullName: '',
      companyName: '',
      phone: '',
      email: '',
      businessDescription: ''
    };
  }
}

<section #section id="contacto" [class]="'w-full flex flex-col lg:flex-row items-center gap-8 md:gap-12 lg:gap-[122px] px-4 md:px-12 lg:px-[130px] py-8 md:py-16 lg:py-[93px] mb-8 md:mb-16 lg:mb-24 bg-[#ffffff17] rounded-[30px] md:rounded-[60px] transition-all duration-1000 ' + (isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10')">
  <div class="flex flex-col w-full lg:w-[724px] items-start gap-6 md:gap-11">
    <h2 class="self-stretch font-medium text-white text-2xl md:text-3xl lg:text-5xl tracking-[0] leading-tight md:leading-[57px] flex items-center justify-center [font-family:'Funnel_Display',Helvetica]">
      ¿Listo para llevar tu negocio al siguiente nivel?
    </h2>

    <p class="w-full lg:w-[538px] [font-family:'Degular-Regular',Helvetica] font-normal text-white text-base md:text-xl lg:text-2xl tracking-[0] leading-relaxed md:leading-[37px]">
      Déjanos tus datos y te ayudaremos a resolver tus dudas o iniciar el proceso de contratación.
      <br><br>
      Te contactaremos lo más pronto posible para apoyarte en todo lo que necesites.
    </p>
  </div>

  <div class="w-full lg:w-[520px] bg-[#fefefe] rounded-[20px] md:rounded-[40px] border-0">
    <div class="pt-8 md:pt-10 lg:pt-12 px-4 md:px-6 lg:px-[50px] pb-8 md:pb-10 lg:pb-[50px]">
      <form (ngSubmit)="onSubmit()" class="flex flex-col gap-4 md:gap-5 lg:gap-5">
        <!-- Nombre Completo -->
        <div class="flex flex-col gap-3 md:gap-4 lg:gap-4">
          <label for="fullName" class="[font-family:'Degular-Semibold',Helvetica] text-base md:text-lg lg:text-xl tracking-[0.49px] leading-[17.1px] font-normal text-[#1a1a1a]">
            Nombre completo
          </label>
          <div class="relative">
            <input
              id="fullName"
              name="fullName"
              [(ngModel)]="formData.name"
              placeholder="Ingresa tu nombre completo"
              class="w-full h-12 md:h-12 lg:h-[50px] rounded-[7.31px] border-[1.22px] border-[#d2d2d2] [font-family:'Inter',Helvetica] font-normal text-[#767676] text-sm md:text-sm lg:text-base tracking-[-0.35px] leading-[31.7px] pr-12 md:pr-[55px] px-4">
            <svg class="absolute right-[19px] top-1/2 -translate-y-1/2 w-6 h-6 text-[#767676]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
            </svg>
          </div>
        </div>

        <!-- Nombre de la Empresa -->
        <div class="flex flex-col gap-3 md:gap-4 lg:gap-4">
          <label for="companyName" class="[font-family:'Degular-Semibold',Helvetica] text-base md:text-lg lg:text-xl tracking-[0.49px] leading-[17.1px] font-normal text-[#1a1a1a]">
            Nombre de la empresa
          </label>
          <div class="relative">
            <input
              id="companyName"
              name="companyName"
              [(ngModel)]="formData.business"
              placeholder="Ingresa el nombre de tu empresa"
              class="w-full h-12 md:h-12 lg:h-[50px] rounded-[7.31px] border-[1.22px] border-[#d2d2d2] [font-family:'Inter',Helvetica] font-normal text-[#767676] text-sm md:text-sm lg:text-base tracking-[-0.35px] leading-[31.7px] pr-12 md:pr-[55px] px-4">
            <svg class="absolute right-[19px] top-1/2 -translate-y-1/2 w-6 h-6 text-[#767676]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
            </svg>
          </div>
        </div>

        <!-- Teléfono -->
        <div class="flex flex-col gap-3 md:gap-4 lg:gap-4">
          <label for="phone" class="[font-family:'Degular-Semibold',Helvetica] text-base md:text-lg lg:text-xl tracking-[0.49px] leading-[17.1px] font-normal text-[#1a1a1a]">
            Teléfono de contacto
          </label>
          <div class="relative">
            <input
              id="phone"
              name="phone"
              [(ngModel)]="formData.phone"
              placeholder="Ingresa tu número de teléfono"
              class="w-full h-12 md:h-12 lg:h-[50px] rounded-[7.31px] border-[1.22px] border-[#d2d2d2] [font-family:'Inter',Helvetica] font-normal text-[#767676] text-sm md:text-sm lg:text-base tracking-[-0.35px] leading-[31.7px] pr-12 md:pr-[55px] px-4">
            <svg class="absolute right-[19px] top-1/2 -translate-y-1/2 w-6 h-6 text-[#767676]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
            </svg>
          </div>
        </div>

        <!-- Email -->
        <div class="flex flex-col gap-3 md:gap-4 lg:gap-4">
          <label for="email" class="[font-family:'Degular-Semibold',Helvetica] text-base md:text-lg lg:text-xl tracking-[0.49px] leading-[17.1px] font-normal text-[#1a1a1a]">
            Correo electrónico
          </label>
          <div class="relative">
            <input
              id="email"
              name="email"
              type="email"
              [(ngModel)]="formData.email"
              placeholder="Ingresa tu correo electrónico"
              class="w-full h-12 md:h-12 lg:h-[50px] rounded-[7.31px] border-[1.22px] border-[#d2d2d2] [font-family:'Inter',Helvetica] font-normal text-[#767676] text-sm md:text-sm lg:text-base tracking-[-0.35px] leading-[31.7px] pr-12 md:pr-[55px] px-4">
            <svg class="absolute right-[19px] top-1/2 -translate-y-1/2 w-6 h-6 text-[#767676]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
            </svg>
          </div>
        </div>

        <!-- Descripción del Negocio -->
        <div class="flex flex-col gap-3 md:gap-4 lg:gap-4">
          <label for="businessDescription" class="[font-family:'Degular-Semibold',Helvetica] text-base md:text-lg lg:text-xl tracking-[0.49px] leading-[17.1px] font-normal text-[#1a1a1a]">
            Cuéntanos un poco sobre tu negocio
          </label>
          <textarea
            id="businessDescription"
            name="businessDescription"
            [(ngModel)]="formData.description"
            placeholder="Describe lo que hace tu negocio"
            class="w-full h-24 md:h-24 lg:h-[90px] rounded-[7.31px] border-[1.22px] border-[#d2d2d2] [font-family:'Inter',Helvetica] font-normal text-[#767676] text-sm md:text-sm lg:text-base tracking-[-0.35px] leading-[31.7px] resize-none px-4 py-3">
          </textarea>
        </div>

        <button
          type="submit"
          class="h-12 md:h-12 lg:h-[50px] mt-2 md:mt-3 rounded-[70px] bg-[linear-gradient(343deg,rgba(255,136,170,1)_0%,rgba(107,78,230,1)_73%)] [font-family:'Urbanist',Helvetica] font-semibold text-white text-base md:text-lg lg:text-xl tracking-[0] leading-[31.7px] hover:opacity-90 transition-opacity cursor-pointer">
          Enviar
        </button>
      </form>
    </div>
  </div>
</section>
