// src/app/web/testimonials-section/testimonials-section.component.ts
import { Component, AfterViewInit, ElementRef, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';

interface FAQItem {
  id: string;
  question: string;
  answer: string;
  isOpen: boolean;
}

@Component({
  selector: 'app-testimonials-section',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './testimonials-section.component.html',
  styleUrls: ['./testimonials-section.component.css']
})
export class TestimonialsSectionComponent implements AfterViewInit {
  @ViewChild('section') section!: ElementRef;
  isVisible = false;

  faqItems: FAQItem[] = [
    {
      id: 'item-1',
      question: '¿Qué es +Breve?',
      answer: '+Breve es una plataforma digital que permite a negocios gestionar y cobrar suscripciones de manera simple, automática y segura. Reúne herramientas para manejar pagos, suscriptores y reportes sin complicaciones.',
      isOpen: false
    },
    {
      id: 'item-2',
      question: '¿Cuánto cuesta usar +Breve?',
      answer: 'En +Breve cobramos una suscripción mensual según el número de transacciones de tu negocio, más una comisión por transacción exitosa. Para conocer el detalle, agenda una reunión con uno de nuestros founders.',
      isOpen: false
    },
    {
      id: 'item-3',
      question: '¿Cuánto tiempo toma implementar +Breve en mi negocio?',
      answer: 'Puedes empezar a usar +Breve en minutos. El proceso de registro es rápido y el flujo de suscripción está listo para configurarse y comenzar a recibir pagos el mismo día.',
      isOpen: false
    },
    {
      id: 'item-4',
      question: '¿Necesito conocimientos técnicos para usar +Breve?',
      answer: 'No necesitas conocimientos técnicos avanzados. La plataforma está diseñada para ser intuitiva y sencilla; puedes gestionar todo desde un panel amigable. Si necesitas ayuda, te acompañamos en el proceso.',
      isOpen: false
    },
    {
      id: 'item-5',
      question: '¿Qué métodos de pago pueden usar mis clientes?',
      answer: 'Tus clientes pueden pagar con tarjeta de crédito, débito, PSE, Nequi y transferencia Bancolombia gracias a la integración con Wompi.',
      isOpen: false
    },
    {
      id: 'item-6',
      question: '¿Cómo recibo el dinero de las suscripciones?',
      answer: 'El dinero de tus suscripciones se transfiere directamente a tu cuenta bancaria, habitualmente en el día hábil siguiente a cada pago realizado.',
      isOpen: false
    }
  ];

  ngAfterViewInit() {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          this.isVisible = true;
        }
      },
      { threshold: 0.1 }
    );

    if (this.section) {
      observer.observe(this.section.nativeElement);
    }
  }

  toggleItem(item: FAQItem) {
    item.isOpen = !item.isOpen;
  }
}

<section #section id="preguntas-frecuentes" [class]="'flex flex-col lg:flex-row w-full items-start justify-between gap-8 md:gap-12 lg:gap-16 px-4 md:px-12 lg:px-[73px] py-16 md:py-24 lg:py-40 bg-white transition-all duration-1000 ' + (isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10')">
  <h2 class="w-full lg:w-[703px] font-semibold text-[#3d1c87] text-4xl md:text-[64px] tracking-[-0.5px] md:tracking-[-3.00px] leading-tight md:leading-[53.1px] [font-family:'Funnel_Display',Helvetica]">
    Preguntas frecuentes
  </h2>

  <div class="flex flex-col w-full lg:w-[873.86px] items-start gap-4">
    <div *ngFor="let item of faqItems" class="w-full">
      <div class="bg-[#f7f5fd] rounded-[16.26px] border-none px-6 py-4">
        <button
          (click)="toggleItem(item)"
          class="w-full flex items-center justify-between hover:no-underline font-degular font-normal text-[#272727] text-[20px] md:text-lg lg:text-[22.4px] tracking-[0] leading-relaxed md:leading-[33.5px] text-left transition-all"
          [attr.aria-expanded]="item.isOpen">
          <span class="flex-1 pr-4">{{ item.question }}</span>
          <svg
            [class]="'w-6 h-6 flex-shrink-0 transition-transform duration-200 ' + (item.isOpen ? 'rotate-180' : '')"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
          </svg>
        </button>

        <div
          [class]="'overflow-hidden transition-all duration-300 ' + (item.isOpen ? 'max-h-96 opacity-100 mt-4' : 'max-h-0 opacity-0')"
          [style.max-height]="item.isOpen ? '24rem' : '0'">
          <p class="font-degular font-normal text-[#272727] text-sm md:text-base lg:text-[18px] tracking-[0] leading-relaxed md:leading-[27px]">
            {{ item.answer }}
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

// project/src/screens/LandingPage/sections/TestimonialsSection/TestimonialsSection.tsx
import React from "react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "../../../../components/ui/accordion";
import { useScrollAnimation } from "../../../../hooks/useScrollAnimation";

const faqItems = [
  {
    id: "item-1",
    question: "¿Qué es +Breve?",
    answer: "+Breve es una plataforma digital que permite a negocios gestionar y cobrar suscripciones de manera simple, automática y segura. Reúne herramientas para manejar pagos, suscriptores y reportes sin complicaciones.",
  },
  {
    id: "item-2",
    question: "¿Cuánto cuesta usar +Breve?",
    answer: "+Breve tiene un modelo de cobro por transacción, sin costos fijos mensuales. Solo pagas una pequeña comisión por cada suscripción cobrada exitosamente.",
  },
  {
    id: "item-3",
    question: "¿Cuánto tiempo toma implementar +Breve en mi negocio?",
    answer: "Puedes empezar a usar +Breve en minutos. El proceso de registro es rápido y el flujo de suscripción está listo para configurarse y comenzar a recibir pagos el mismo día.",
  },
  {
    id: "item-4",
    question: "¿Necesito conocimientos técnicos para usar +Breve?",
    answer: "No necesitas conocimientos técnicos avanzados. La plataforma está diseñada para ser intuitiva y sencilla; puedes gestionar todo desde un panel amigable. Si necesitas ayuda, te acompañamos en el proceso.",
  },
  {
    id: "item-5",
    question: "¿Qué métodos de pago pueden usar mis clientes?",
    answer: "Tus clientes pueden pagar con tarjeta de crédito, débito, PSE, Nequi y transferencia Bancolombia gracias a la integración con Wompi.",
  },
  {
    id: "item-6",
    question: "¿Cómo recibo el dinero de las suscripciones?",
    answer: "El dinero de tus suscripciones se transfiere directamente a tu cuenta bancaria, habitualmente en el día hábil siguiente a cada pago realizado.",
  },
];

export const TestimonialsSection = (): JSX.Element => {
  const { elementRef, isVisible } = useScrollAnimation();

  return (
    <section
      id="preguntas-frecuentes"
      ref={elementRef}
      className={`flex flex-col lg:flex-row w-full items-start justify-between gap-8 md:gap-12 lg:gap-16 px-4 md:px-12 lg:px-[73px] py-16 md:py-24 lg:py-40 bg-white transition-all duration-1000 ${
        isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'
      }`}>
      <h2 className="w-full lg:w-[703px] font-semibold text-[#3d1c87] text-4xl md:text-[64px] tracking-[-0.5px] md:tracking-[-3.00px] leading-tight md:leading-[53.1px] [font-family:'Funnel_Display',Helvetica]">
        Preguntas frecuentes
      </h2>

      <div className="flex flex-col w-full lg:w-[873.86px] items-start gap-4">
        <Accordion type="single" collapsible className="w-full space-y-4">
          {faqItems.map((item) => (
            <AccordionItem
              key={item.id}
              value={item.id}
              className="bg-[#f7f5fd] rounded-[16.26px] border-none px-6 py-2"
            >
              <AccordionTrigger className="hover:no-underline [font-family:'Degular-Regular',Helvetica] font-normal text-[#272727] text-[20px] md:text-lg lg:text-[22.4px] tracking-[0] leading-relaxed md:leading-[33.5px] text-left">
                {item.question}
              </AccordionTrigger>
              <AccordionContent className="[font-family:'Degular-Regular',Helvetica] font-normal text-[#272727] text-sm md:text-base lg:text-[18px] tracking-[0] leading-relaxed md:leading-[27px] pt-2">
                {item.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
};
